on:
  release:
    types: [created]

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Build and publish
        run: |
         npm ci
         npm run build -- -release-version ${{github.ref_name}}
         cd build
         npx vsce publish --no-dependencies -p ${{ secrets.VSCODE_MARKETPLACE_ACCESSTOKEN }}
      # - name: Publish to Open VSX Registry
      #   uses: HaaLeo/publish-vscode-extension@v1
      #   with:
      #     pat: ${{ secrets.OPEN_VSX_TOKEN }}